print("=== Age calculator ===")
name = input("Name : ")
curyear = input("Current year (AD) : ")
yearofbirth = input("birth year (AD) : ")
age = int(curyear) - int(yearofbirth) 
print(name + " age is " + str(age) + " years")